add rocky branch to features.yaml
This patch adds the rocky branch to features.yaml so that rocky branch
patches can land, for example [1] that currently fails with:
ERROR: branch not allowed by features matrix: rocky

[1] https://review.openstack.org/#/c/584078/

Change-Id: I235c6c3ad81dff916a65cf8b97152621812fa102